# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15
    container_name: my-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=testdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-app
    environment:
      - NODE_ENV=production
      # 請確認以下 DATABASE_URL 與你的程式中讀取資料庫的設定相符
      - DATABASE_URL=postgres://postgres:123456@db:5432/testdb
      - PUBLIC_DIR=/app/dist/public     # ← 確保 serveStatic 里拿到 process.env.PUBLIC_DIR 时不是 undefined
      - UPLOAD_DIR=/app/uploads         # ← 如果代码里还会 path.resolve(process.env.UPLOAD_DIR, …)
    depends_on:
      - db
    ports:
      - "5000:5000"
    # 如果你需要開發時直接看到程式碼變動，可自行啟用 volumes：
    # volumes:
    #   - ./:/app
    #   - /app/node_modules

volumes:
  pgdata:
