# docker-compose.prod.yml
version: '3.8'

services:
  db:
    image: postgres:15
    container_name: my-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=testdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-app
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:123456@db:5432/testdb
      - PUBLIC_DIR=/app/dist/public
      - UPLOAD_DIR=/app/uploads
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    # 生產環境不掛載 volume，直接使用 build 完整映像
    # command: 可不指定，因為 Dockerfile 已經有 CMD
